print("Hello, I am a bot. What's your name?")
name = input("Enter your name: ")
print("Nice to meet you,", name)
print("I hope you are fine.")
print("Do you know about sliced string in python? Actually, I can slice your name.")
print("Just tell me, how many words will you take from your name. Remember, you have", len(name), "letters in your name")
slice_number = int(input("Number: "))
print("This is your sliced name:", name[0:slice_number])
print("Oh no!, I am running out of battery. I have to charge my self. Bye!!")